### Listar todas las categorías
GET http://localhost:3000/api/classes

###

### Crear una nueva categoría
POST http://localhost:3000/api/classes
Content-Type: application/json

{
  "code": "123",
  "name": "Hola",
  "section": "Mundo",
  "location": "Honduras",
  "schedule": "Hoy a tal hora"
}

###

### Probar error: Nombre duplicado (P2002 - HTTP 409)
POST http://localhost:3000/api/categorias
Content-Type: application/json

{
  "nombre": "Electrónica"
}

###

### Probar error: Nombre obligatorio (HTTP 400)
POST http://localhost:3000/api/categorias
Content-Type: application/json

{
  "nombre": ""
}
