### Listar todas las clases
GET http://localhost:3000/api/classes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3OTA0ODk0NjQsImV4cCI6MTc5MDQ5MzA2NH0.tuodhgjOm-_H97LfN2KIWJ2ct4-ukPGSkPQopDk4e9U

### Listar todas las clases true
GET http://localhost:3000/api/classes?active=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3OTA0ODk0NjQsImV4cCI6MTc5MDQ5MzA2NH0.tuodhgjOm-_H97LfN2KIWJ2ct4-ukPGSkPQopDk4e9U

### Listar todas las clases false
GET http://localhost:3000/api/classes?active=false

### Crear una nueva categoría
POST http://localhost:3000/api/classes
Content-Type: application/json

{
  "code": "123",
  "name": "Hola",
  "section": "Mundo",
  "location": "Honduras",
  "schedule": "Hoy a tal hora"
}

###

### Crear otra categoria
POST http://localhost:3000/api/classes
Content-Type: application/json

{
  "code": "654",
  "name": "Adios",
  "section": "Mundo",
  "location": "Guatemala",
  "schedule": "Mañana a otra hora"
}


### Obtener una clase por id

GET http://localhost:3000/api/classes/1

### Update una estación
PUT http://localhost:3000/api/classes/3
Content-Type: application/json

{
  "active": true
}

### Delete una clase
DELETE http://localhost:3000/api/classes/2
