### Listar todas las clases
GET http://localhost:3000/api/classes

### Listar todas las clases true
GET http://localhost:3000/api/classes?active=true

### Listar todas las clases false
GET http://localhost:3000/api/classes?active=false

### Crear una nueva categoría
POST http://localhost:3000/api/classes
Content-Type: application/json

{
  "code": "123",
  "name": "Hola",
  "section": "Mundo",
  "location": "Honduras",
  "schedule": "Hoy a tal hora"
}

###

### Crear otra categoria
POST http://localhost:3000/api/classes
Content-Type: application/json

{
  "code": "654",
  "name": "Adios",
  "section": "Mundo",
  "location": "Guatemala",
  "schedule": "Mañana a otra hora"
}


### Obtener una clase por id

GET http://localhost:3000/api/classes/3

### Update una estación
PUT http://localhost:3000/api/classes/3
Content-Type: application/json

{
  "active": false
}

### Delete una clase
DELETE http://localhost:3000/api/classes/2
