### Listar todas las estaciones
GET http://localhost:3000/api/allstations

###

### Crear una estación
POST http://localhost:3000/api/stations
Content-Type: application/json

{
  "name": "Bueno",
  "code": "hola",
  "location": "FI",
  "operatingSystem": "WINDOWS",
  "classId": 3
}

###

### Crear otra estación
POST http://localhost:3000/api/stations
Content-Type: application/json

{
  "name": "Estación 2",
  "code": "asdf12",
  "location": "FabLab",
  "operatingSystem": "ASD",
  "classId": 1
}

###

### Obtener una estación

GET http://localhost:3000/api/stations/3

###

### Update una estación
PUT http://localhost:3000/api/stations/3
Content-Type: application/json

{
  "name": "nuevo2",
  "classId": 1,
  "code": "bueno"
}

###

### Update ignored

PATCH http://localhost:3000/api/stations/3
Content-Type: application/json

{
  "ignored": false
}

###

### Get estaciones por clase
GET http://localhost:3000/api/stations?classId=1&status=critico